public enum TokenType {
    FOREACH, AS, VARIABLE, IDENTIFIANT,
    NOMBRE,
    PARENTHESE_OUVRANTE, PARENTHESE_FERMANTE,
    ACCOLADE_OUVRANTE, ACCOLADE_FERMANTE,
    POINT_VIRGULE,
    AFFECTATION, INCREMENTATION, 
    EGALITE, INFERIEUR, SUPERIEUR,
    INFERIEUR_EGALE, SUPERIEUR_EGALE,
    DIFFERENT,
    NOM, PRENOM,
    FIN
}
